# `.nav.yml` is provided by https://lukasgeiter.github.io/mkdocs-awesome-nav
nav:
  - Installation: installation.md
  - Create your first component: your_first_component.md
  - Adding JS and CSS: adding_js_and_css.md
  - Components in templates: components_in_templates.md
  - Parametrising components: parametrising_components.md
  - Adding slots: adding_slots.md
  - Rendering components: rendering_components.md
  - Going beyond:
    - Choose tag formatting: choose_tag_formatting.md
    - Choose render modes: choose_render_modes.md
    - Choose context mode: choose_render_modes.md
    - Install components: install_components.md
    - Install extensions: install_extensions.md
    - Vue setup
